use_frameworks!

target 'ChelseabandSDK_Example' do
  pod 'ChelseabandSDK', :path => '../'
  pod 'RxBluetoothKit', '~> 6.0.0'
  pod 'SnapKit'
  pod 'RxCocoa'
  pod 'DropDown'

  target 'ChelseabandSDK_Tests' do
    inherit! :search_paths
    pod 'RxTest'
  end
end
